import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Suspense } from "react";
import { AlertDialogProvider } from "@/components/providers/alert-provider";
import { FullLoadingProvider } from "@/components/providers/full-loading-provider";
import { HelperProvider } from "@/components/providers/helper-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "BEARHOUSE Branch Config",
  description: "Generated by IT",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Suspense fallback={<div></div>}>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <AlertDialogProvider>
            <FullLoadingProvider>
              <HelperProvider>{children}</HelperProvider>
            </FullLoadingProvider>
          </AlertDialogProvider>
        </body>
      </html>
    </Suspense>
  );
}
